name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ 권한 추가


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Node.js 설정 (버전은 필요에 따라 수정 가능)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행
      - name: Build Project
        run: npm run build

      # 5. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}  # ✅ GitHub 인증을 위한 토큰
          BRANCH: ${{ secrets.BRANCH }}  # ✅ 배포할 브랜치
          COMMIT_AUTHOR: ${{ secrets.COMMIT_AUTHOR }}  # ✅ 커밋 작성자
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}  # ✅ 커밋 이메일
          COMMIT_MESSAGE: ${{ secrets.COMMIT_MESSAGE }}  # ✅ 커밋 메시지
          TARGET_REPO: ${{ secrets.TARGET_REPO }}  # ✅ 타깃 레포
        run: |
          mkdir temp
          cd temp
          git init -b $BRANCH
          git config --global user.email "$COMMIT_EMAIL"
          git config --global user.name "$COMMIT_AUTHOR"
          
          git remote add origin https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO }}
          
          echo "원격 레포지터리 파일 다운로드"
          git pull https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO }} $BRANCH
          echo "배포 파일로 덮어쓰기"
          cp -rf ../dist/* ./

          echo "원격 레포지터리에 파일전송"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push -u origin $BRANCH
          
          
          
